version: '3.9'

services:
  xre-dev:
    hostname: xre-dev
    tty: true
    privileged: true
    cap_add:
      - ALL
    working_dir: /root
    build:
      context: ./dev
      dockerfile: Dockerfile
    volumes:
      - ./engine:/root/engine
      - ./pp:/root/pp
      - ./tools:/root/tools
    ports:
      - '0.0.0.0:8000:3000'
    expose:
      - 7000
