version: '3.9'
services:
  xre-dev:
    hostname: xre-dev
    tty: true
    privileged: true
    cap_add:
      - ALL
    working_dir: /root
    build:
      context: ./dev
      dockerfile: Dockerfile
    volumes:
      - ./engine:/root/engine
      - ./tools:/root/tools
      - ./shared:/root/shared

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - '9009:3000'
    volumes:
      - ./webapp:/app
      - /app/node_modules
      - ./shared:/app/shared
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
    depends_on:
      - xre-dev
