name: tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  install-script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install xre
        run: ./__scripts__/install.sh

      - name: Try xre
        run: xre -h

  syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install sparse

      - name: Run sparse
        run: >
          sparse      \
            -Wno-decl \
            -Wsparse-error \
            -I ./incs \
            $(find . -name "*.c" -not -path "*/unit-tests/*")

  tester-valgrind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build xre (debug)
        run: make

      - name: Run tester.sh
        working-directory: __tools__/tester
        run: >
          chmod +x run
          && mv ../../xre .
          && chmod +x xre
          && ./run

  tester-asan:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install timeout
        run: brew install coreutils

      - name: Build xre (debug)
        run: make g

      - name: Run tester.sh
        working-directory: __tools__/tester
        run: >
          chmod +x run
          && mv ../../xre .
          && chmod +x xre
          && ./run

