name: tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make

  tester:
    runs-on: ubuntu-latest

    steps:
      - name: make
        uses: actions/checkout@v2

      - name: build xre
        run: make

      - name: run tester.sh
        working-directory: tester
        run: chmod +x run && mv ../xre . && chmod +x xre && ./run

  memory:
    runs-on: ubuntu-latest

    steps:
      - name: make
        uses: actions/checkout@v2

      - name: build xre
        run: make g

      - name: run tester.sh
        working-directory: tester
        run: chmod +x run && mv ../xre . && chmod +x xre && ./run

  syntax:
    runs-on: ubuntu-latest

    steps:
      - name: install sparse
        uses: actions/checkout@v2

      - name: run sparse
        run: sudo apt-get install sparse && sparse -I ./incs $(find . -name "*.c")
